# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems = let
    zfsRoot = "zroot";
  in {
    "/" = {
      device = "${zfsRoot}/root";
      fsType = "zfs";
    };
    "/nix" = {
      device = "${zfsRoot}/nix";
      fsType = "zfs";
    };
    "/var" = {
      device = "${zfsRoot}/var";
      fsType = "zfs";
    };
    "/home" = {
      device = "${zfsRoot}/home";
      fsType = "zfs";
    };
    "/boot" = {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };
    "/home/henrikvt/.local/share/Steam/steamapps" = {
      device = "${zfsRoot}/steam";
      fsType = "zfs";
    };
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
