name: Flake Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@v13
      - name: Check cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run Checks
        run: nix flake check --no-build
