name: Flake Format

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@v13
      - name: Check cache
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-store
      - name: Format flake
        run: nix fmt .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto-format Flake
          commit_user_name: Format Bot
          commit_user_email: actions@github.com
          commit_author: Format Bot <actions@github.com>
