name: Flake Format

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@v13
      - name: Check cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Format flake
        run: nix fmt .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto-format Flake
          commit_author: Format Bot <actions@github.com>
