name: Daily Flake Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@v13
#      - name: Check cache
#        uses: actions/cache/restore@v4
#        with:
#          path: /nix/store
#          key: ${{ runner.os }}-nix-store
      - name: Update flake inputs
        run: nix flake update
      - name: Ensure the flake passes checks
        run: nix flake check
      - name: Copy all flake inputs to store for caching
        run: nix flake archive
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto-update Flake
          commit_user_name: Update Bot
          commit_user_email: actions@github.com
          commit_author: Update Bot <actions@github.com>
